name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests in Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4  # Use the same Go version as your local setup

    - name: Install dependencies
      run: |
        cd backend
        go mod tidy

    - name: Run tests in backend directory
      run: |
        cd backend
        go test ./... -v
